# PyTorch - Layer Types

Explore and research different PyTorch layer types.

# Notebook Setup

## Imports

In [1]:
# Import Standard Libraries
import torch

# Layer Types

## Linear Layer

In [10]:
# Check linear layer parameters
linear = torch.nn.Linear(3, 2)

for index, param in enumerate(linear.parameters()):
    # Switch between weights and bias
    parameter_name = 'Weights' if index == 0 else 'Bias'
    print('Parameter: ', parameter_name)
    print('Shape: ', param.shape)
    print(param)
    print()

# Check weights
print('Linear Layer weights -', linear.weight)

Parameter:  Weights
Shape:  torch.Size([2, 3])
Parameter containing:
tensor([[-0.1807, -0.4746,  0.2120],
        [ 0.1208,  0.4870, -0.4575]], requires_grad=True)

Parameter:  Bias
Shape:  torch.Size([2])
Parameter containing:
tensor([-0.0179, -0.3414], requires_grad=True)

Linear Layer weights - Parameter containing:
tensor([[-0.1807, -0.4746,  0.2120],
        [ 0.1208,  0.4870, -0.4575]], requires_grad=True)
