# Introduction

Experiment with PyTorch and in particular with Tensors.

In [2]:
# Import Standard Libraries
import torch

# Definition

## Integer Tensors

In [4]:
# 1-D Tensor or Vector
tensor = torch.tensor([1, 2, 3])

In [5]:
tensor

tensor([1, 2, 3])

In [6]:
# 2-D Tensor or Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [7]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

## Float Tensors

In [10]:
# Create a float tensor
tensor_float = torch.FloatTensor([1, 2, 3])
tensor_float_2 = torch.tensor([1, 2, 3], dtype=torch.float)

In [11]:
tensor_float

tensor([1., 2., 3.])

In [12]:
tensor_float_2

tensor([1., 2., 3.])

## Double Tensors

In [13]:
# Create a double tensor
tensor_double = torch.DoubleTensor([1, 2, 3])
tensor_double_2 = torch.tensor([1, 2, 3], dtype=torch.double)

In [14]:
tensor_double

tensor([1., 2., 3.], dtype=torch.float64)

In [17]:
tensor_double_2

tensor([1., 2., 3.], dtype=torch.float64)

# Shape

In [9]:
# Shape and size() give the same results
print(tensor.shape)
print(matrix.shape)
print(tensor.size())
print(matrix.size())

torch.Size([3])
torch.Size([2, 3])
torch.Size([3])
torch.Size([2, 3])


# Statistics

In [22]:
# Get the mean and std
tensor_double.mean()

tensor(2., dtype=torch.float64)

In [23]:
tensor_double.std()

tensor(1., dtype=torch.float64)

# Reshape

In [ ]:
# It is done through the method 