# Introduction

Experiment with PyTorch and in particular with Tensors.

They are similar to NumPy's ndarrays, but Tensors can run on GPUs or other hardware accelerators.

Tensors are also optimised for Automatic Differentiation.

In [1]:
# Import Standard Libraries
import torch
import numpy as np

# Definition

## Integer Tensors

In [2]:
# 1-D Tensor or Vector
tensor = torch.tensor([1, 2, 3])

In [3]:
tensor

tensor([1, 2, 3])

In [4]:
# 2-D Tensor or Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [5]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

## Float Tensors

In [6]:
# Create a float tensor
tensor_float = torch.FloatTensor([1, 2, 3])
tensor_float_2 = torch.tensor([1, 2, 3], dtype=torch.float)

In [7]:
tensor_float

tensor([1., 2., 3.])

In [8]:
tensor_float_2

tensor([1., 2., 3.])

## Double Tensors

In [9]:
# Create a double tensor
tensor_double = torch.DoubleTensor([1, 2, 3])
tensor_double_2 = torch.tensor([1, 2, 3], dtype=torch.double)

In [10]:
tensor_double

tensor([1., 2., 3.], dtype=torch.float64)

In [11]:
tensor_double_2

tensor([1., 2., 3.], dtype=torch.float64)

In [10]:
# Convert integer to double
tensor_integer = torch.tensor([1, 2, 3], dtype=torch.int)
print(tensor_integer.to(torch.double))

tensor([1., 2., 3.], dtype=torch.float64)


## Empty

In [2]:
torch.empty(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Tensor Like

In [5]:
base = torch.tensor([1, 2, 3])

In [8]:
print(torch.empty_like(base))
print(torch.zeros_like(base))
print(torch.ones_like(base))

tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([1, 1, 1])


# Shape

In [12]:
# Shape and size() give the same results
print(tensor.shape)
print(matrix.shape)
print(tensor.size())
print(matrix.size())

torch.Size([3])
torch.Size([2, 3])
torch.Size([3])
torch.Size([2, 3])


# Statistics

In [13]:
# Get the mean and std
tensor_double.mean()

tensor(2., dtype=torch.float64)

In [14]:
tensor_double.std()

tensor(1., dtype=torch.float64)

# Reshape

In [15]:
# It is done through the method 'view'
tensor_double.view(-1, 1)

tensor([[1.],
        [2.],
        [3.]], dtype=torch.float64)

In [16]:
# The '-1' means that the dimension has to be inferred from the second one
matrix.view(-1, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

# Copying

In [12]:
base = torch.tensor([1, 2, 3, 4])
copy = base.clone()
print(copy)

tensor([1, 2, 3, 4])


# Random

In [17]:
# Random numbers from normal distribution
torch.randn(4, 4)

tensor([[-0.3907,  0.5070,  0.1158,  1.4555],
        [-1.8903,  1.0267, -1.1397, -0.9969],
        [ 0.8901, -0.1865, -0.2482,  0.3541],
        [ 0.7096,  0.0199, -0.5409,  0.3529]])

In [18]:
# Random integer numbers between 1 and 10
torch.randint(1, 10, (4, 2))

tensor([[5, 3],
        [9, 8],
        [3, 2],
        [5, 5]])

In [19]:
# Generate a random tensor with the same size of another one
tensor_random = torch.randn(4, 4)
print(torch.randn_like(tensor_random, dtype=torch.double))

tensor([[ 0.0412, -0.7726, -1.4671,  0.9161],
        [ 0.6138,  1.0242,  1.1921,  0.0278],
        [-0.5629,  1.5592, -0.0185, -1.4586],
        [ 0.1430, -1.7010,  0.7583,  0.7188]], dtype=torch.float64)


# Operations

In [20]:
# Add
torch.add(torch.tensor([1, 2, 3], dtype=torch.double), 
          torch.tensor([4, 5, 6], dtype=torch.double))

tensor([5., 7., 9.], dtype=torch.float64)

# Numpy Integrations

In [21]:
# Convert from tensor to numpy array
numpy_array = torch.ones(5).numpy()

In [22]:
type(numpy_array)

numpy.ndarray

In [23]:
# Convert from numpy to tensor
tensor_from_numpy = torch.from_numpy(np.ndarray([1, 2, 3]))

In [24]:
type(tensor_from_numpy)

torch.Tensor

# GPU Usage

## CUDA

In [25]:
# Move tensor to GPU
tensor_float = tensor_float.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [27]:
# Check if CUDA is available
torch.cuda.is_available()

False

## General Accelerator

### Move to Device

In [27]:
if torch.accelerator.is_available():
    print('Accelerator is available: ', torch.accelerator.current_accelerator())
    tensor = tensor.to(torch.accelerator.current_accelerator())

Accelerator is available:  mps


### Create Already on the Device

In [13]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

Device: mps


In [14]:
x = torch.rand(2, 2, device=my_device)
print(x)

tensor([[0.0341, 0.9939],
        [0.2020, 0.8159]], device='mps:0')
