# Introduction

Experiment with PyTorch and in particular with Tensors.

In [1]:
# Import Standard Libraries
import torch
import numpy as np

# Definition

## Integer Tensors

In [2]:
# 1-D Tensor or Vector
tensor = torch.tensor([1, 2, 3])

In [3]:
tensor

tensor([1, 2, 3])

In [4]:
# 2-D Tensor or Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [5]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

## Float Tensors

In [6]:
# Create a float tensor
tensor_float = torch.FloatTensor([1, 2, 3])
tensor_float_2 = torch.tensor([1, 2, 3], dtype=torch.float)

In [7]:
tensor_float

tensor([1., 2., 3.])

In [8]:
tensor_float_2

tensor([1., 2., 3.])

## Double Tensors

In [9]:
# Create a double tensor
tensor_double = torch.DoubleTensor([1, 2, 3])
tensor_double_2 = torch.tensor([1, 2, 3], dtype=torch.double)

In [10]:
tensor_double

tensor([1., 2., 3.], dtype=torch.float64)

In [11]:
tensor_double_2

tensor([1., 2., 3.], dtype=torch.float64)

# Shape

In [12]:
# Shape and size() give the same results
print(tensor.shape)
print(matrix.shape)
print(tensor.size())
print(matrix.size())

torch.Size([3])
torch.Size([2, 3])
torch.Size([3])
torch.Size([2, 3])


# Statistics

In [13]:
# Get the mean and std
tensor_double.mean()

tensor(2., dtype=torch.float64)

In [14]:
tensor_double.std()

tensor(1., dtype=torch.float64)

# Reshape

In [15]:
# It is done through the method 'view'
tensor_double.view(-1, 1)

tensor([[1.],
        [2.],
        [3.]], dtype=torch.float64)

In [16]:
# The '-1' means that the dimension has to be inferred from the second one
matrix.view(-1, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

# Random

In [17]:
# Random numbers from normal distribution
torch.randn(4, 4)

tensor([[-1.8830, -1.7305, -0.3838, -0.6446],
        [ 0.5705, -0.7423,  0.4478,  0.9230],
        [ 0.5368,  1.5204,  0.4083,  0.8357],
        [-2.4958, -0.1774, -1.3885, -1.4901]])

In [18]:
# Random integer numbers between 1 and 10
torch.randint(1, 10, (4, 2))

tensor([[6, 9],
        [7, 2],
        [8, 8],
        [8, 5]])

In [19]:
# Generate a random tensor with the same size of another one
tensor_random = torch.randn(4, 4)
print(torch.randn_like(tensor_random, dtype=torch.double))

tensor([[-0.5977,  1.0083, -1.4834, -0.1746],
        [-1.1579, -1.1544,  0.4036, -0.0921],
        [ 0.0988,  1.2316,  0.2352, -1.1992],
        [ 0.0081, -1.4409,  0.6197,  0.8233]], dtype=torch.float64)


# Operations

In [20]:
# Add
torch.add(torch.tensor([1, 2, 3], dtype=torch.double), 
          torch.tensor([4, 5, 6], dtype=torch.double))

tensor([5., 7., 9.], dtype=torch.float64)

# Numpy Integrations

In [21]:
# Convert from tensor to numpy array
numpy_array = torch.ones(5).numpy()

In [22]:
type(numpy_array)

numpy.ndarray

In [23]:
# Convert from numpy to tensor
tensor_from_numpy = torch.from_numpy(np.ndarray([1, 2, 3]))

In [24]:
type(tensor_from_numpy)

torch.Tensor

# GPU Usage

In [26]:
# Move tensor to GPU
tensor_float = tensor_float.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [27]:
# Check if CUDA is available
torch.cuda.is_available()

False