# Introduction

Experiment with PyTorch and in particular with Tensors.

In [2]:
# Import Standard Libraries
import torch

# Definition

## Integer Tensors

In [4]:
# 1-D Tensor or Vector
tensor = torch.tensor([1, 2, 3])

In [5]:
tensor

tensor([1, 2, 3])

In [6]:
# 2-D Tensor or Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [7]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

## Float Tensors

In [10]:
# Create a float tensor
tensor_float = torch.FloatTensor([1, 2, 3])
tensor_float_2 = torch.tensor([1, 2, 3], dtype=torch.float)

In [11]:
tensor_float

tensor([1., 2., 3.])

In [12]:
tensor_float_2

tensor([1., 2., 3.])

## Double Tensors

In [13]:
# Create a double tensor
tensor_double = torch.DoubleTensor([1, 2, 3])
tensor_double_2 = torch.tensor([1, 2, 3], dtype=torch.double)

In [14]:
tensor_double

tensor([1., 2., 3.], dtype=torch.float64)

In [17]:
tensor_double_2

tensor([1., 2., 3.], dtype=torch.float64)

# Shape

In [9]:
# Shape and size() give the same results
print(tensor.shape)
print(matrix.shape)
print(tensor.size())
print(matrix.size())

torch.Size([3])
torch.Size([2, 3])
torch.Size([3])
torch.Size([2, 3])


# Statistics

In [22]:
# Get the mean and std
tensor_double.mean()

tensor(2., dtype=torch.float64)

In [23]:
tensor_double.std()

tensor(1., dtype=torch.float64)

# Reshape

In [24]:
# It is done through the method 'view'
tensor_double.view(-1, 1)

tensor([[1.],
        [2.],
        [3.]], dtype=torch.float64)

In [26]:
# The '-1' means that the dimension has to be inferred from the second one
matrix.view(-1, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

# Random

In [28]:
# Random numbers from normal distribution
torch.randn(4, 4)

tensor([[ 0.4830, -0.4618, -0.9178,  0.7573],
        [ 0.5485, -0.2027, -1.9606, -0.0810],
        [ 0.6288,  0.1336,  1.3865, -1.9920],
        [ 0.2363, -0.9792,  0.0117, -0.5216]])

In [37]:
# Random integer numbers between 1 and 10
torch.randint(1, 10, (4, 2))

tensor([[8, 9],
        [8, 4],
        [6, 6],
        [8, 6]])

In [39]:
# Generate a random tensor with the same size of another one
tensor_random = torch.randn(4, 4)
print(torch.randn_like(tensor_random, dtype=torch.double))

tensor([[-2.0249,  0.6718,  1.1783,  0.0496],
        [ 0.8409, -1.1505,  0.3878,  0.5574],
        [-0.3427,  0.6600,  1.1552, -0.5180],
        [-0.2376,  0.2543,  0.7970, -1.3231]], dtype=torch.float64)


# Operations

In [40]:
# Add
torch.add(torch.tensor([1, 2, 3], dtype=torch.double), 
          torch.tensor([4, 5, 6], dtype=torch.double))

tensor([5., 7., 9.], dtype=torch.float64)