# Introduction

Experiment with PyTorch Loss Functions.

In [15]:
# Import Standard Libraries
import torch
import torch.nn as nn

In [16]:
# Define a tensor of possible output layer values: 4 values with 5 features
tensor_1 = torch.randn(4, 5)

In [17]:
tensor_1

tensor([[ 0.6564, -1.2322,  1.8523,  1.3146, -1.0642],
        [-0.2401,  0.2339, -0.4977,  0.8021, -0.0224],
        [-0.0341,  0.9484, -0.5104, -0.0370,  1.5323],
        [ 2.4812, -0.7941,  0.2984, -1.1028,  0.1910]])

In [18]:
# Define the label for applying the loss function
# NOTE: The shape should be the same as the tensor_1
label = torch.randn(4, 5)

In [19]:
label

tensor([[-0.2279, -1.3853, -0.6009, -0.1746, -0.3740],
        [ 0.3180,  1.3059, -1.2588,  0.3353, -1.4413],
        [-1.1685, -1.7911, -0.9912,  0.2887, -0.5451],
        [ 1.1822, -1.6947,  1.5271,  0.7561, -1.1159]])

# MSE

In [20]:
# Define the MSE
# NOTE: 'reduction' defines the value to return (e.g., 'sum' returns a double value, while 'none' returns a tensor (N, *))
mse = nn.MSELoss(reduction='none')

In [21]:
# Compute the MSE
loss_mse = mse(tensor_1, label)

In [22]:
loss_mse

tensor([[0.7821, 0.0235, 6.0183, 2.2178, 0.4764],
        [0.3115, 1.1493, 0.5793, 0.2179, 2.0131],
        [1.2868, 7.5050, 0.2312, 0.1061, 4.3153],
        [1.6875, 0.8110, 1.5095, 3.4554, 1.7082]])

In [23]:
(tensor_1[0][0] - label[0][0]) ** 2

tensor(0.7821)

In [24]:
# Let's try the mean reduction
mse_mean = nn.MSELoss(reduction='mean')

In [25]:
loss_mse_mean = mse_mean(tensor_1, label)

In [26]:
loss_mse_mean

tensor(1.8203)

# Binary Cross-Entropy

In [27]:
# Define the labels
# NOTE: Initialise a matrix 4 x 5 with zeros and then randomly fill it with 0 and 1 (random_(0, 2))
label = torch.zeros(4, 5).random_(0, 2)

In [28]:
label

tensor([[1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 0., 0., 1.],
        [1., 0., 1., 1., 0.]])

In [29]:
# Since we're not using BCE with Logits, we need that the input of the BCE comes from a Sigmoid function
# NOTE: BCE with Logits applies the Sigmoid function internally
sigmoid = nn.Sigmoid()

In [33]:
# Define the BCE Loss
bce = nn.BCELoss(reduction='mean')

In [37]:
bce_loss = bce(sigmoid(tensor_1), label)

In [38]:
bce_loss

tensor(0.5792)

In [39]:
bce_with_logits = nn.BCEWithLogitsLoss(reduction='mean')

In [40]:
bce_with_logits_loss = bce_with_logits(tensor_1, label)

In [41]:
bce_with_logits_loss

tensor(0.5792)

Note that the results between BCE and BCE with Logits is exactly the same, because BCE with Logits applies the Sigmoid funciton internally. While for BCE we used the Sigmoid explicitly.