# Introduction

Experiment with PyTorch Loss Functions.

In [1]:
# Import Standard Libraries
import torch
import torch.nn as nn

In [2]:
# Define a tensor of possible output layer values: 4 values with 5 features
tensor_1 = torch.randn(4, 5)

In [3]:
tensor_1

tensor([[ 0.3514,  0.4033, -0.5721,  1.7951,  0.0087],
        [-0.8152, -1.8897, -0.5892, -1.5432, -0.2141],
        [-0.6241,  0.1374, -1.0267, -0.8622,  0.0456],
        [ 0.6935,  0.2812,  2.7240,  0.7654, -1.1467]])

In [4]:
# Define the label for applying the loss function
# NOTE: The shape should be the same as the tensor_1
label = torch.randn(4, 5)

In [5]:
label

tensor([[-1.0847, -0.0467, -0.6488, -0.8116, -0.3826],
        [ 2.6226, -0.2000,  1.2818, -1.7590,  2.0832],
        [ 1.0578,  1.8883, -1.5645, -0.0974,  0.1165],
        [-1.5433, -0.1044,  2.5224, -0.6962,  0.9168]])

# MSE

In [6]:
# Define the MSE
# NOTE: 'reduction' defines the value to return (e.g., 'sum' returns a double value, while 'none' returns a tensor (N, *))
mse = nn.MSELoss(reduction='none')

In [7]:
# Compute the MSE
loss_mse = mse(tensor_1, label)

In [8]:
loss_mse

tensor([[2.0622e+00, 2.0250e-01, 5.8804e-03, 6.7948e+00, 1.5307e-01],
        [1.1818e+01, 2.8552e+00, 3.5008e+00, 4.6562e-02, 5.2776e+00],
        [2.8288e+00, 3.0656e+00, 2.8930e-01, 5.8489e-01, 5.0238e-03],
        [5.0030e+00, 1.4866e-01, 4.0648e-02, 2.1363e+00, 4.2581e+00]])

In [9]:
(tensor_1[0][0] - label[0][0]) ** 2

tensor(2.0622)