# Introduction
The notebook is intended to experiment with the different TensorFlow APIs

In [12]:
# Import Standard Libraries
import os
import numpy as np
import tensorflow as tf

# Suppress warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Read Data

In [4]:
# Define a dataset
X = tf.constant(range(10), dtype=tf.float32)
Y = 2 * X + 10

# Dataset API

## Create

In [8]:
# Create a dataset
dataset = tf.data.Dataset.from_tensor_slices((X, Y))

## Fetch

In [13]:
# Retrieve the data samples
for x, y in dataset:
    print(f'{x} - {y}')

0.0 - 10.0
1.0 - 12.0
2.0 - 14.0
3.0 - 16.0
4.0 - 18.0
5.0 - 20.0
6.0 - 22.0
7.0 - 24.0
8.0 - 26.0
9.0 - 28.0


## Batch and Epochs

In [14]:
# Define batch size and epochs
batch_size = 3
epochs = 6

In [15]:
# Add batches and epochs
dataset = dataset.repeat(epochs).batch(batch_size, drop_remainder=True)

In [17]:
# Reitreve the batches for the epochs
for batch_x, batch_y in dataset:
    print(f'{batch_x} - {batch_y}')

[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]
[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]
