# Introduction
The notebook is intended to experiment with the different TensorFlow APIs

In [12]:
# Import Standard Libraries
import os
import numpy as np
import tensorflow as tf

# Suppress warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Read Data

In [4]:
# Define a dataset
X = tf.constant(range(10), dtype=tf.float32)
Y = 2 * X + 10

# Dataset API

## Create

In [8]:
# Create a dataset
dataset = tf.data.Dataset.from_tensor_slices((X, Y))

## Fetch

In [13]:
# Retrieve the data samples
for x, y in dataset:
    print(f'{x} - {y}')

0.0 - 10.0
1.0 - 12.0
2.0 - 14.0
3.0 - 16.0
4.0 - 18.0
5.0 - 20.0
6.0 - 22.0
7.0 - 24.0
8.0 - 26.0
9.0 - 28.0


## Batch and Epochs

In [14]:
# Define batch size and epochs
batch_size = 3
epochs = 6

In [15]:
# Add batches and epochs
dataset = dataset.repeat(epochs).batch(batch_size, drop_remainder=True)

In [17]:
# Reitreve the batches for the epochs
for batch_x, batch_y in dataset:
    print(f'{batch_x} - {batch_y}')

[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]
[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]


# Linear Regression Training

In [18]:
def loss_mse(X, Y, w0, b):
    """
    Compute the Loss as Mean Squared Error
    """
    
    # Predict the y value
    y_predicted = w0 * X + b

    # Compute the error
    errors = (y_predicted - Y)**2

    # Compute the mean
    mse = tf.reduce_mean(errors)
    
    return mse

In [19]:
def compute_derivate_terms(X, Y, w0, b):
    """
    Compute the derivative terms for w0 and b
    """
    
    with tf.GradientTape() as tape:
        loss = loss_mse(X, Y, w0, b)
    return tape.gradient(loss, [w0, b])

In [20]:
# Initialise w0 and b
w0, b = tf.Variable(0.0), tf.Variable(0.0)

# Set learning rate
learning_rate = 0.001

# Create bigger dataset
dataset = tf.data.Dataset.from_tensor_slices((X, Y)).repeat(250).batch(2, drop_remainder=True)

for step, (X_batch, Y_batch) in enumerate(dataset):

    # Compute the derivate terms
    dw0, db = compute_derivate_terms(X_batch, Y_batch, w0, b)

    # Update w0 and b
    w0.assign_sub(dw0 * learning_rate)
    b.assign_sub(db * learning_rate)

    # Print loss every 100 steps
    if step % 100 == 0:
        loss = loss_mse(X_batch, Y_batch, w0, b)
        print(f'Step {step} - Loss {loss}')

2023-06-08 21:28:26.118222: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [10]
	 [[{{node Placeholder/_1}}]]


Step 0 - Loss 121.37281799316406
Step 100 - Loss 67.96109008789062
Step 200 - Loss 60.568275451660156
Step 300 - Loss 54.036888122558594
Step 400 - Loss 48.209930419921875
Step 500 - Loss 43.01130676269531
Step 600 - Loss 38.37327575683594
Step 700 - Loss 34.235374450683594
Step 800 - Loss 30.54366683959961
Step 900 - Loss 27.25004768371582
Step 1000 - Loss 24.31158447265625
Step 1100 - Loss 21.689990997314453
Step 1200 - Loss 19.35108184814453
