# Introduction
The notebook is intended to experiment with the different TensorFlow APIs

In [16]:
# Import Standard Libraries
import os

import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

from sklearn.model_selection import train_test_split

# Suppress warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Read Data

In [2]:
# Define a dataset
X = tf.constant(range(10), dtype=tf.float32)
Y = 2 * X + 10

## Pet Finder Mini Toy

In [3]:
# Read required data petfinder_mini_toy
petfinder_mini_toy = pd.read_csv('./../../data/petfinder-mini.csv')

In [14]:
petfinder_mini_toy.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

In [15]:
# Create target variable
petfinder_mini_toy['target'] = np.where(petfinder_mini_toy['AdoptionSpeed']==4, 0, 1)

# Drop unused columns
petfinder_mini_toy = petfinder_mini_toy.drop(columns=['AdoptionSpeed', 'Description'])

In [18]:
# Split train + validation + test
petfinder_mini_toy_train, petfinder_mini_toy_test = train_test_split(petfinder_mini_toy, test_size=0.2)
petfinder_mini_toy_train, petfinder_mini_toy_validation = train_test_split(petfinder_mini_toy_train, test_size=0.2)

print(len(petfinder_mini_toy_train), 'train examples')
print(len(petfinder_mini_toy_validation), 'validation examples')
print(len(petfinder_mini_toy_test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


# Dataset API

## Create

In [4]:
# Create a dataset
dataset = tf.data.Dataset.from_tensor_slices((X, Y))

## Fetch

In [5]:
# Retrieve the data samples
for x, y in dataset:
    print(f'{x} - {y}')

0.0 - 10.0
1.0 - 12.0
2.0 - 14.0
3.0 - 16.0
4.0 - 18.0
5.0 - 20.0
6.0 - 22.0
7.0 - 24.0
8.0 - 26.0
9.0 - 28.0


2023-06-13 19:37:35.960429: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [10]
	 [[{{node Placeholder/_1}}]]


## Batch and Epochs

In [6]:
# Define batch size and epochs
batch_size = 3
epochs = 6

In [7]:
# Add batches and epochs
dataset = dataset.repeat(epochs).batch(batch_size, drop_remainder=True)

In [8]:
# Reitreve the batches for the epochs
for batch_x, batch_y in dataset:
    print(f'{batch_x} - {batch_y}')

[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]
[0. 1. 2.] - [10. 12. 14.]
[3. 4. 5.] - [16. 18. 20.]
[6. 7. 8.] - [22. 24. 26.]
[9. 0. 1.] - [28. 10. 12.]
[2. 3. 4.] - [14. 16. 18.]
[5. 6. 7.] - [20. 22. 24.]
[8. 9. 0.] - [26. 28. 10.]
[1. 2. 3.] - [12. 14. 16.]
[4. 5. 6.] - [18. 20. 22.]
[7. 8. 9.] - [24. 26. 28.]


2023-06-13 19:37:36.026819: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [10]
	 [[{{node Placeholder/_1}}]]


## Read CSV

In [9]:
# Define feature columns
features = ['date', 
            'country', 
            'store', 
            'product']

# Define labels
labels = ['num_sold']

# Read data from csv
dataset_csv = tf.data.experimental.make_csv_dataset(file_pattern='./../../data/books_sold_train.csv', batch_size=4)

In [10]:
# Fetch data
for step, (row) in enumerate(dataset_csv):

    print(row['row_id'])

    if step == 3:
        break

2023-06-13 19:37:36.118080: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [1]
	 [[{{node Placeholder/_0}}]]
2023-06-13 19:37:36.118521: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_7' with dtype int32 and shape [1]
	 [[{{node Placeholder/_7}}]]


tf.Tensor([2662 2322 8868 3475], shape=(4,), dtype=int32)
tf.Tensor([5627 8225 7237 4607], shape=(4,), dtype=int32)
tf.Tensor([7890 1647 8350 2818], shape=(4,), dtype=int32)
tf.Tensor([4393  373 1462 4099], shape=(4,), dtype=int32)


## Create Dataset from DataFrame

In [22]:
def dataframe_to_dataset(data: pd.DataFrame, 
                         label_column: str, 
                         shuffle:bool = True, 
                         epochs:int = None, 
                         batch_size:int = 32):

    # Ensure to not work on the original dataframe
    data = data.copy()

    # Extract the label
    labels = data.pop(label_column)

    # Create the dataset
    dataset = tf.data.Dataset.from_tensor_slices(dict(data), labels)

    # Shuffle dataset
    if shuffle:
        dataset = ds.shuffle(buffer_size=len(data))

    # Repeat for epochs
    if epochs:
        dataset = dataset.repeat(epochs)

    # Add batches
    if batch_size:

        # Add batches 
        dataset = dataset.batch(batch_size)
        
        # Prefect method ensures to prepare the next element while the current is being processed
        dataset = dataset.prefecth(batch_size)
                             
    return dataset          

In [27]:
petfinder_mini_toy_dataset = dataframe_to_dataset(petfinder_mini_toy, 'target', epochs=4)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

# Linear Regression Training

In [11]:
def loss_mse(X, Y, w0, b):
    """
    Compute the Loss as Mean Squared Error
    """
    
    # Predict the y value
    y_predicted = w0 * X + b

    # Compute the error
    errors = (y_predicted - Y)**2

    # Compute the mean
    mse = tf.reduce_mean(errors)
    
    return mse

In [12]:
def compute_derivate_terms(X, Y, w0, b):
    """
    Compute the derivative terms for w0 and b
    """
    
    with tf.GradientTape() as tape:
        loss = loss_mse(X, Y, w0, b)
    return tape.gradient(loss, [w0, b])

In [13]:
# Initialise w0 and b
w0, b = tf.Variable(0.0), tf.Variable(0.0)

# Set learning rate
learning_rate = 0.001

# Create bigger dataset
dataset = tf.data.Dataset.from_tensor_slices((X, Y)).repeat(250).batch(2, drop_remainder=True)

for step, (X_batch, Y_batch) in enumerate(dataset):

    # Compute the derivate terms
    dw0, db = compute_derivate_terms(X_batch, Y_batch, w0, b)

    # Update w0 and b
    w0.assign_sub(dw0 * learning_rate)
    b.assign_sub(db * learning_rate)

    # Print loss every 100 steps
    if step % 100 == 0:
        loss = loss_mse(X_batch, Y_batch, w0, b)
        print(f'Step {step} - Loss {loss}')

2023-06-13 19:37:36.294767: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype float and shape [10]
	 [[{{node Placeholder/_1}}]]


Step 0 - Loss 121.37281799316406
Step 100 - Loss 67.96109008789062
Step 200 - Loss 60.568275451660156
Step 300 - Loss 54.036888122558594
Step 400 - Loss 48.209930419921875
Step 500 - Loss 43.01130676269531
Step 600 - Loss 38.37327575683594
Step 700 - Loss 34.235374450683594
Step 800 - Loss 30.54366683959961
Step 900 - Loss 27.25004768371582
Step 1000 - Loss 24.31158447265625
Step 1100 - Loss 21.689990997314453
Step 1200 - Loss 19.35108184814453
